container:
  image: ubuntu:22.04
  cpu: 8
  memory: 32G
  greedy: true 

task:
  name: "LineageOS VirtIO Build"
  timeout_in: 1200m
  install_script: |
    apt-get update && apt-get install -y \
    bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs \
    gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev \
    lib32z1-dev libdw-dev libelf-dev libgnutls28-dev lz4 libsdl1.2-dev libssl-dev \
    libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc \
    xxd zip zlib1g-dev python3-mako python-is-python3 wget ca-certificates
    mkdir -p /usr/local/bin
    curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
    chmod a+x /usr/local/bin/repo
  build_script: |
    git config --global user.name "CirrusCI"
    git config --global user.email "ci@cirrus.com"
    chmod +x build.sh
    ./build.sh
  artifacts:
    path: "lineage/out/target/product/virtio_arm64only/*.zip"